// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mist/chat/v1/chat_packet.proto
// Protobuf Java Version: 4.33.4

package com.xyrisdev.mist.messaging.chat.packet;

/**
 * Protobuf type {@code mist.chat.v1.ChatPacket}
 */
@com.google.protobuf.Generated
public final class ChatPacket extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:mist.chat.v1.ChatPacket)
    ChatPacketOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "ChatPacket");
  }
  // Use ChatPacket.newBuilder() to construct.
  private ChatPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ChatPacket() {
    serverId_ = "";
    senderId_ = "";
    messageJson_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xyrisdev.mist.messaging.chat.packet.ChatPacketOuterClass.internal_static_mist_chat_v1_ChatPacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xyrisdev.mist.messaging.chat.packet.ChatPacketOuterClass.internal_static_mist_chat_v1_ChatPacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xyrisdev.mist.messaging.chat.packet.ChatPacket.class, com.xyrisdev.mist.messaging.chat.packet.ChatPacket.Builder.class);
  }

  public static final int SERVER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serverId_ = "";
  /**
   * <code>string server_id = 1 [json_name = "serverId"];</code>
   * @return The serverId.
   */
  @java.lang.Override
  public java.lang.String getServerId() {
    java.lang.Object ref = serverId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverId_ = s;
      return s;
    }
  }
  /**
   * <code>string server_id = 1 [json_name = "serverId"];</code>
   * @return The bytes for serverId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServerIdBytes() {
    java.lang.Object ref = serverId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object senderId_ = "";
  /**
   * <code>string sender_id = 2 [json_name = "senderId"];</code>
   * @return The senderId.
   */
  @java.lang.Override
  public java.lang.String getSenderId() {
    java.lang.Object ref = senderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderId_ = s;
      return s;
    }
  }
  /**
   * <code>string sender_id = 2 [json_name = "senderId"];</code>
   * @return The bytes for senderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderIdBytes() {
    java.lang.Object ref = senderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_JSON_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object messageJson_ = "";
  /**
   * <code>string message_json = 3 [json_name = "messageJson"];</code>
   * @return The messageJson.
   */
  @java.lang.Override
  public java.lang.String getMessageJson() {
    java.lang.Object ref = messageJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageJson_ = s;
      return s;
    }
  }
  /**
   * <code>string message_json = 3 [json_name = "messageJson"];</code>
   * @return The bytes for messageJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageJsonBytes() {
    java.lang.Object ref = messageJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, serverId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, senderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageJson_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, messageJson_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, serverId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, senderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageJson_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, messageJson_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xyrisdev.mist.messaging.chat.packet.ChatPacket)) {
      return super.equals(obj);
    }
    com.xyrisdev.mist.messaging.chat.packet.ChatPacket other = (com.xyrisdev.mist.messaging.chat.packet.ChatPacket) obj;

    if (!getServerId()
        .equals(other.getServerId())) return false;
    if (!getSenderId()
        .equals(other.getSenderId())) return false;
    if (!getMessageJson()
        .equals(other.getMessageJson())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getServerId().hashCode();
    hash = (37 * hash) + SENDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSenderId().hashCode();
    hash = (37 * hash) + MESSAGE_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getMessageJson().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xyrisdev.mist.messaging.chat.packet.ChatPacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mist.chat.v1.ChatPacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mist.chat.v1.ChatPacket)
      com.xyrisdev.mist.messaging.chat.packet.ChatPacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xyrisdev.mist.messaging.chat.packet.ChatPacketOuterClass.internal_static_mist_chat_v1_ChatPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xyrisdev.mist.messaging.chat.packet.ChatPacketOuterClass.internal_static_mist_chat_v1_ChatPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xyrisdev.mist.messaging.chat.packet.ChatPacket.class, com.xyrisdev.mist.messaging.chat.packet.ChatPacket.Builder.class);
    }

    // Construct using com.xyrisdev.mist.messaging.chat.packet.ChatPacket.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      serverId_ = "";
      senderId_ = "";
      messageJson_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xyrisdev.mist.messaging.chat.packet.ChatPacketOuterClass.internal_static_mist_chat_v1_ChatPacket_descriptor;
    }

    @java.lang.Override
    public com.xyrisdev.mist.messaging.chat.packet.ChatPacket getDefaultInstanceForType() {
      return com.xyrisdev.mist.messaging.chat.packet.ChatPacket.getDefaultInstance();
    }

    @java.lang.Override
    public com.xyrisdev.mist.messaging.chat.packet.ChatPacket build() {
      com.xyrisdev.mist.messaging.chat.packet.ChatPacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xyrisdev.mist.messaging.chat.packet.ChatPacket buildPartial() {
      com.xyrisdev.mist.messaging.chat.packet.ChatPacket result = new com.xyrisdev.mist.messaging.chat.packet.ChatPacket(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xyrisdev.mist.messaging.chat.packet.ChatPacket result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.serverId_ = serverId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.senderId_ = senderId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.messageJson_ = messageJson_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xyrisdev.mist.messaging.chat.packet.ChatPacket) {
        return mergeFrom((com.xyrisdev.mist.messaging.chat.packet.ChatPacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xyrisdev.mist.messaging.chat.packet.ChatPacket other) {
      if (other == com.xyrisdev.mist.messaging.chat.packet.ChatPacket.getDefaultInstance()) return this;
      if (!other.getServerId().isEmpty()) {
        serverId_ = other.serverId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSenderId().isEmpty()) {
        senderId_ = other.senderId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getMessageJson().isEmpty()) {
        messageJson_ = other.messageJson_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              serverId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              senderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              messageJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object serverId_ = "";
    /**
     * <code>string server_id = 1 [json_name = "serverId"];</code>
     * @return The serverId.
     */
    public java.lang.String getServerId() {
      java.lang.Object ref = serverId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string server_id = 1 [json_name = "serverId"];</code>
     * @return The bytes for serverId.
     */
    public com.google.protobuf.ByteString
        getServerIdBytes() {
      java.lang.Object ref = serverId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string server_id = 1 [json_name = "serverId"];</code>
     * @param value The serverId to set.
     * @return This builder for chaining.
     */
    public Builder setServerId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serverId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string server_id = 1 [json_name = "serverId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearServerId() {
      serverId_ = getDefaultInstance().getServerId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string server_id = 1 [json_name = "serverId"];</code>
     * @param value The bytes for serverId to set.
     * @return This builder for chaining.
     */
    public Builder setServerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serverId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object senderId_ = "";
    /**
     * <code>string sender_id = 2 [json_name = "senderId"];</code>
     * @return The senderId.
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender_id = 2 [json_name = "senderId"];</code>
     * @return The bytes for senderId.
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender_id = 2 [json_name = "senderId"];</code>
     * @param value The senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      senderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string sender_id = 2 [json_name = "senderId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderId() {
      senderId_ = getDefaultInstance().getSenderId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string sender_id = 2 [json_name = "senderId"];</code>
     * @param value The bytes for senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      senderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object messageJson_ = "";
    /**
     * <code>string message_json = 3 [json_name = "messageJson"];</code>
     * @return The messageJson.
     */
    public java.lang.String getMessageJson() {
      java.lang.Object ref = messageJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message_json = 3 [json_name = "messageJson"];</code>
     * @return The bytes for messageJson.
     */
    public com.google.protobuf.ByteString
        getMessageJsonBytes() {
      java.lang.Object ref = messageJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message_json = 3 [json_name = "messageJson"];</code>
     * @param value The messageJson to set.
     * @return This builder for chaining.
     */
    public Builder setMessageJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageJson_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string message_json = 3 [json_name = "messageJson"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageJson() {
      messageJson_ = getDefaultInstance().getMessageJson();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string message_json = 3 [json_name = "messageJson"];</code>
     * @param value The bytes for messageJson to set.
     * @return This builder for chaining.
     */
    public Builder setMessageJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageJson_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:mist.chat.v1.ChatPacket)
  }

  // @@protoc_insertion_point(class_scope:mist.chat.v1.ChatPacket)
  private static final com.xyrisdev.mist.messaging.chat.packet.ChatPacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xyrisdev.mist.messaging.chat.packet.ChatPacket();
  }

  public static com.xyrisdev.mist.messaging.chat.packet.ChatPacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatPacket>
      PARSER = new com.google.protobuf.AbstractParser<ChatPacket>() {
    @java.lang.Override
    public ChatPacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatPacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatPacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xyrisdev.mist.messaging.chat.packet.ChatPacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

