// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mist/chat/v1/chat_packet.proto
// Protobuf Java Version: 4.33.4

package com.xyrisdev.mist.messaging.chat.packet;

@com.google.protobuf.Generated
public interface ChatPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mist.chat.v1.ChatPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string server_id = 1 [json_name = "serverId"];</code>
   * @return The serverId.
   */
  java.lang.String getServerId();
  /**
   * <code>string server_id = 1 [json_name = "serverId"];</code>
   * @return The bytes for serverId.
   */
  com.google.protobuf.ByteString
      getServerIdBytes();

  /**
   * <code>string sender_id = 2 [json_name = "senderId"];</code>
   * @return The senderId.
   */
  java.lang.String getSenderId();
  /**
   * <code>string sender_id = 2 [json_name = "senderId"];</code>
   * @return The bytes for senderId.
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string message_json = 3 [json_name = "messageJson"];</code>
   * @return The messageJson.
   */
  java.lang.String getMessageJson();
  /**
   * <code>string message_json = 3 [json_name = "messageJson"];</code>
   * @return The bytes for messageJson.
   */
  com.google.protobuf.ByteString
      getMessageJsonBytes();
}
