// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mist/chat/v1/chat_packet.proto
// Protobuf Java Version: 4.33.4

package com.xyrisdev.mist.messaging.chat.packet;

@com.google.protobuf.Generated
public final class ChatPacketOuterClass extends com.google.protobuf.GeneratedFile {
  private ChatPacketOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "ChatPacketOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mist_chat_v1_ChatPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mist_chat_v1_ChatPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036mist/chat/v1/chat_packet.proto\022\014mist.c" +
      "hat.v1\"i\n\nChatPacket\022\033\n\tserver_id\030\001 \001(\tR" +
      "\010serverId\022\033\n\tsender_id\030\002 \001(\tR\010senderId\022!" +
      "\n\014message_json\030\003 \001(\tR\013messageJsonB+\n\'com" +
      ".xyrisdev.mist.messaging.chat.packetP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mist_chat_v1_ChatPacket_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_mist_chat_v1_ChatPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mist_chat_v1_ChatPacket_descriptor,
        new java.lang.String[] { "ServerId", "SenderId", "MessageJson", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
